# Jellyfin media server configuration
image:
  repository: jellyfin/jellyfin
  tag: "10.8.13"
  pullPolicy: IfNotPresent

replicaCount: 1

# Service configuration
service:
  type: ClusterIP
  port: 8096

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: jellyfin.homelab.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Persistence for Jellyfin config and cache
persistence:
  config:
    enabled: true
    size: 5Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  cache:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteOnce

# Media storage (you can mount external volumes here)
media:
  # For development, we'll create a small media volume
  enabled: true
  size: 50Gi
  storageClass: ""
  accessMode: ReadWriteOnce

# Resource limits
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

# Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Environment variables
env:
  - name: TZ
    value: "UTC"
  - name: JELLYFIN_PublishedServerUrl
    value: "http://jellyfin.homelab.local"

# Node selector for hardware transcoding (if available)
nodeSelector: {}

# Tolerations for dedicated media nodes
tolerations: []

# Affinity rules
affinity: {}
