nextcloud:
  image:
    repository: nextcloud
    tag: 27.1.4-apache
    
  # Admin user configuration
  nextcloud:
    host: nextcloud.homelab.local
    username: admin
    password: admin123  # Change for production!
    
    # Enable additional apps
    extraInitContainers: []
    
    # PHP configuration
    phpConfigs:
      uploadLimit.ini: |
        upload_max_filesize = 16G
        post_max_size = 16G
        max_input_time = 3600
        max_execution_time = 3600
        memory_limit = 1G
    
    # Default phone region
    defaultPhoneRegion: US
    
    # Email configuration (optional)
    mail:
      enabled: false
  
  # Ingress configuration
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: nextcloud.homelab.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  
  # Persistence for Nextcloud data
  persistence:
    enabled: true
    size: 50Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  
  # PostgreSQL database
  postgresql:
    enabled: true
    auth:
      username: nextcloud
      password: nextcloud123
      database: nextcloud
    primary:
      persistence:
        enabled: true
        size: 8Gi
  
  # Redis for caching
  redis:
    enabled: true
    auth:
      enabled: false
    master:
      persistence:
        enabled: false
  
  # Resource limits
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  
  # Cronjob for maintenance
  cronjob:
    enabled: true
    schedule: "*/15 * * * *"
  
  # Liveness and readiness probes
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
