apiVersion: v2
name: prometheus
description: Prometheus monitoring stack for homelab
type: application
version: 0.1.0
appVersion: "2.47.2"

dependencies:
  - name: kube-prometheus-stack
    version: "54.0.1"
    repository: https://prometheus-community.github.io/helm-charts
