# Custom Authentic deployment values
image:
  repository: ghcr.io/goauthentik/server
  tag: "2024.10.1"
  
replicaCount: 1

# PostgreSQL database
postgresql:
  enabled: true
  auth:
    username: authentic
    password: authentic123
    database: authentic
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Redis for caching and sessions
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

# Authentic configuration
authentic:
  # Secret key for sessions
  secretKey: "change-me-in-production-very-long-secret-key-here"
  
  # Email configuration (optional)
  email:
    host: ""
    port: 587
    username: ""
    password: ""
    from: "authentic@homelab.local"
    
  # LDAP settings (if needed)
  ldap:
    enabled: false

# Service configuration
service:
  type: ClusterIP
  port: 9000

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: auth.homelab.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resources
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

# Storage for media files
persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
