apiVersion: v2
name: argocd
description: ArgoCD GitOps deployment for homelab
type: application
version: 0.1.0
appVersion: "2.8.4"

dependencies:
  - name: argo-cd
    version: "5.46.7"
    repository: https://argoproj.github.io/argo-helm
