minio:
  # Deployment mode - standalone for development
  mode: standalone
  
  # Root user credentials (change for production!)
  rootUser: minioadmin
  rootPassword: minioadmin123
  
  # Persistence configuration
  persistence:
    enabled: true
    size: 20Gi
    storageClass: ""  # Use default storage class
  
  # Service configuration
  service:
    type: ClusterIP
    port: 9000
    
  # Console service
  consoleService:
    type: ClusterIP
    port: 9001
  
  # Ingress for MinIO API
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: minio.homelab.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  
  # Ingress for MinIO Console
  consoleIngress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: minio-console.homelab.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
  
  # Resources
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m
  
  # Security context
  securityContext:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  
  # Enable metrics for monitoring
  metrics:
    serviceMonitor:
      enabled: false  # Enable later with monitoring stack
  
  # Default buckets to create
  buckets:
    - name: nextcloud
      policy: none
      purge: false
    - name: immich
      policy: none
      purge: false
    - name: backups
      policy: none
      purge: false
