# Paperless-ngx document management configuration
image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  tag: "2.2.1"
  pullPolicy: IfNotPresent

replicaCount: 1

# PostgreSQL database
postgresql:
  enabled: true
  auth:
    username: paperless
    password: paperless123
    database: paperless
  primary:
    persistence:
      enabled: true
      size: 8Gi

# Redis for task queue
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: false

# Service configuration
service:
  type: ClusterIP
  port: 8000

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: paperless.homelab.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Persistence for documents and media
persistence:
  data:
    enabled: true
    size: 20Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  media:
    enabled: true
    size: 50Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  consume:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteOnce

# Environment variables
env:
  - name: PAPERLESS_REDIS
    value: "redis://paperless-ngx-redis-master:6379"
  - name: PAPERLESS_DBHOST
    value: "paperless-ngx-postgresql"
  - name: PAPERLESS_DBUSER
    value: "paperless"
  - name: PAPERLESS_DBPASS
    value: "paperless123"
  - name: PAPERLESS_DBNAME
    value: "paperless"
  - name: PAPERLESS_SECRET_KEY
    value: "change-me-in-production-secret-key"
  - name: PAPERLESS_URL
    value: "http://paperless.homelab.local"
  - name: PAPERLESS_ADMIN_USER
    value: "admin"
  - name: PAPERLESS_ADMIN_PASSWORD
    value: "admin123"
  - name: PAPERLESS_OCR_LANGUAGE
    value: "eng"
  - name: PAPERLESS_TIME_ZONE
    value: "UTC"

# Resource limits
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

# Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
